# Generated by Django 5.0.1 on 2024-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Leader', 'leader'), ('Manager', 'manager'), ('Employee', 'employee')], max_length=50),
        ),
    ]
